apiVersion: spark.apache.org/v1alpha1
kind: SparkApplication
metadata:
  name: spark-app
  namespace: etl
spec:
  mainClass: "com.bulatmain.etl.Application"
  jars: "local:///app/classpath/spark-app-0.1.3-SNAPSHOT.jar"
  sparkConf:
    spark.app.name: "spark-app"
    spark.jars.ivy: "/tmp/ivy"
    spark.dynamicAllocation.enabled: "true"
    spark.dynamicAllocation.shuffleTracking.enabled: "true"
    spark.dynamicAllocation.maxExecutors: "3"
    spark.kubernetes.authenticate.driver.serviceAccountName: "spark"
    spark.kubernetes.container.image: "bulatmain/spark-app:0.1.3-SNAPSHOT"
  applicationTolerations:
    resourceRetainPolicy: OnFailure
  runtimeVersions:
    sparkVersion: "3.5.5"